name: Bug Report
description: Use this template to report a bug. Fields marked as required must be completed.
title: "[Bug] "
labels: ["bug", "enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Description
        Please provide the following details to help us resolve the issue. Fields marked as required must be completed.
        
    

  - type: input
    id: device
    attributes:
      label: Device Used to Reproduce (Required)
      description: Specify the device model (e.g., Samsung Galaxy S21, Pixel 6).
      placeholder: Enter device name
    validations:
      required: true

  - type: input
    id: android_version 
    attributes:
      label: Android Version (Required)
      description: Enter the version of Android (e.g., Android 11, Android 12).
      placeholder: Enter Android version
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority of the Issue/Bug (Required)
      description: Select the priority level for the issue.
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce 
    attributes:
      label: Steps to Reproduce (Required)
      description: Provide detailed steps to reproduce the issue.
      placeholder: Enter step-by-step instructions
    validations:
      required: true

  - type: textarea
    id: media_to_upload
    attributes:
      label: Related Screenshots/Media (Optional)
      description: Please upload any relevant screenshots, videos, logs, or provide links to hosted files (e.g., Google Drive, Dropbox, etc.).
      placeholder: Enter a link or upload the files.
