name: Enhancement Request
description: Use this template to suggest improvements or new features for the app.
title: "[Enhancement] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Enhancement Description
        Please provide a detailed description of the enhancement or feature request.

  - type: textarea
    id: enhancement_description
    attributes:
      label: Enhancement Description (Required)
      description: Provide a clear and detailed description of the enhancement or feature you'd like to see.
      placeholder: Enter your enhancement idea here
    validations:
      required: true

  - type: textarea
    id: expected_impact
    attributes:
      label: Expected Impact (Optional)
      description: Describe the potential impact of this enhancement (e.g., improved performance, new functionality, etc.).
      placeholder: Describe the expected impact
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (Optional)
      description: Provide any mockups, examples, or further context that could help us understand your enhancement.
      placeholder: Add any supporting context here
