name: iOS Bug Report
description: Use this template to report a bug for iOS. Fields marked as required must be completed.
title: "[Bug][iOS] "
labels: ["bug", "iOS"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Description
        Please provide the following details to help us resolve the issue. Fields marked as required must be completed.

  - type: input
    id: device
    attributes:
      label: Device Used to Reproduce (Required)
      description: Specify the iOS device model (e.g., iPhone 13, iPad Pro).
      placeholder: Enter device name
    validations:
      required: true

  - type: input
    id: ios_version
    attributes:
      label: iOS Version (Required)
      description: Enter the version of iOS (e.g., iOS 15.6, iOS 16.1).
      placeholder: Enter iOS version
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority of the Issue/Bug (Required)
      description: Select the priority level for the issue.
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce (Required)
      description: Provide detailed steps to reproduce the issue.
      placeholder: Enter step-by-step instructions
    validations:
      required: true

  - type: textarea
    id: media_to_upload
    attributes:
      label: Related Screenshots/Media (Optional)
      description: Please upload any relevant screenshots, videos, logs, or provide links to hosted files (e.g., iCloud, Google Drive, Dropbox, etc.).
      placeholder: Enter a link or upload the files.
